version: '3.8'
services:
  postgresdb:
    image: postgres:15
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - springboot-postgres-network

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    networks:
      - springboot-postgres-network

volumes:
  postgres_data:

networks:
  springboot-postgres-network:
    driver: bridge
